api_authenticate:
    route: /api/authenticate/:username
    module: api
    action: authenticate
    parameters: [ ]
    csrf_enabled: false

api_status:
    route: /api/status
    module: api
    action: status
    parameters: [ ]
    csrf_enabled: false

api_me:
    route: /api/me
    module: api
    action: me
    parameters: [ ]
    csrf_enabled: false

api_list_projects:
    route: /api/projects
    module: api
    action: listProjects
    parameters: [ ]
    csrf_enabled: false

api_project:
    route: /api/projects/:project_key
    module: api
    action: project
    parameters: [ ]
    csrf_enabled: false

api_list_issuetypes:
    route: /api/issuetypes
    module: api
    action: listIssuetypes
    parameters: [ ]
    csrf_enabled: false

api_list_issuefields:
    route: /api/list/issuefields/for/:project_key/type/:issuetype
    module: api
    action: listIssuefields
    parameters: [ ]
    csrf_enabled: false

api_list_fieldvalues:
    route: '/api/list/fieldvalues/for/field/:field_key/*'
    module: api
    action: listFieldvalues
    parameters: [ ]
    csrf_enabled: false

api_issue_edittimespent:
    route: /api/:project_key/issues/:issue_id/timespent/:entry_id
    module: api
    action: issueEditTimeSpent
    parameters: [ ]
    csrf_enabled: false
